[project]
name = "hubla-prod-bq"
version = "0.0.1"
description = "Hubla's production BQ datapackage"
dependencies = [
    "grpcio ~= 1.54.2",
    "protobuf ~= 4.23.2",
    "python-graphql-client ~= 0.4.3",
]
